In [2]:
import numpy as np 

In [11]:
a = np.array([[1,2],[3,4]])
a 

array([[1, 2],
       [3, 4]])

In [12]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [14]:
c = np.concatenate((a,b),axis = 0)
c 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
b1 = np.array([[7],[8]])
d  = np.concatenate((a,b1),axis=1)
d 

array([[1, 2, 7],
       [3, 4, 8]])

In [26]:
x = np.array(
    [
        [[1,2,3,1],[4,5,6,1]],
        [[4,5,6,2],[7,8,9,2]],
        [[4,5,6,2],[7,8,9,2]],
        [[4,5,6,2],[7,8,9,2]],
        [[4,5,6,2],[7,8,9,2]]
    ]
)
print(x.ndim)
print(x.size)
print(x.shape)

3
40
(5, 2, 4)


In [29]:
x1 = x.reshape(2,2,-1)
x1

array([[[1, 2, 3, 1, 4, 5, 6, 1, 4, 5],
        [6, 2, 7, 8, 9, 2, 4, 5, 6, 2]],

       [[7, 8, 9, 2, 4, 5, 6, 2, 7, 8],
        [9, 2, 4, 5, 6, 2, 7, 8, 9, 2]]])

In [35]:
x2 = x.reshape(-1,4,5)
x2

array([[[1, 2, 3, 1, 4],
        [5, 6, 1, 4, 5],
        [6, 2, 7, 8, 9],
        [2, 4, 5, 6, 2]],

       [[7, 8, 9, 2, 4],
        [5, 6, 2, 7, 8],
        [9, 2, 4, 5, 6],
        [2, 7, 8, 9, 2]]])

In [40]:
a = np.arange(12)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
a.reshape(-1,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [58]:
a = np.arange(6)
print(a.shape)
a

(6,)


array([0, 1, 2, 3, 4, 5])

In [59]:
a1 = a[np.newaxis,:]
print(a1.shape)
a1

(1, 6)


array([[0, 1, 2, 3, 4, 5]])

In [61]:
a2 = np.expand_dims(a,axis=1)
print(a2.shape)
a2 

(6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [86]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
             [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a.shape)
a 

(2, 4, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
a1 = np.expand_dims(a,axis=0)
print(a1.shape)
a1

(1, 2, 4, 3)


array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [89]:
a2 = np.expand_dims(a,axis=1)
print(a2.shape)
a2 

(2, 1, 4, 3)


array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [90]:
a3 = np.expand_dims(a,axis=2)
print(a3.shape)
a3 

(2, 4, 1, 3)


array([[[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]],


       [[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]]])

In [93]:
a4 = np.expand_dims(a,axis=3) # 最后一列也可以用-1 
print(a4.shape)
a4  

(2, 4, 3, 1)


array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]],


       [[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

In [101]:
x = np.array([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[1,2,3,4,5],[6,7,8,9,10]]])
print(x.shape)
x[:]

(2, 2, 5)


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [102]:
x[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [105]:
x[0,1,1:5]

array([ 7,  8,  9, 10])

In [107]:
x[x%2==0]

array([ 2,  4,  6,  8, 10,  2,  4,  6,  8, 10])

In [114]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a1 = np.nonzero(a%5==0)
a1 

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))

In [117]:
a2 = np.nonzero(a>5)
print(a2[0])
print(a2[1])
a2 

[1 1 1 2 2 2 2]
[1 2 3 0 1 2 3]


(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [118]:
b = list(zip(a2[0],a2[1]))
b 

[(1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]

In [119]:
np.nonzero(b)

(array([0, 0, 1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1], dtype=int64))

In [129]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.nonzero(a<5)
print(b)
np.nonzero(a[b])

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


(array([0, 1, 2, 3], dtype=int64),)

In [128]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.nonzero(a%5==0)
print(b)
np.nonzero(a[b])

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))


(array([0, 1], dtype=int64),)

In [130]:
a[a%5==0]

array([ 5, 10])

In [132]:
a = np.array([[1,2],
             [3,4]])
b = np.array([[1,2],
             [3,4]])
c = np.vstack((a,b))
c 

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [133]:
c = np.hstack((a,b))
c 

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [153]:
x = np.arange(1,25).reshape(2,12) 
x 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [154]:
x1 = np.hsplit(x,3)
x1 

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [156]:
x2 = np.hsplit(x,(3,4,5))
x2 

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5],
        [17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [159]:
x3 = x.copy()
x3[1,3] = 11
x3 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 11, 17, 18, 19, 20, 21, 22, 23, 24]])

In [161]:
x 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [163]:
x4 = x3[:]
x4[1,4] = 100 
x3 

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  11, 100,  18,  19,  20,  21,  22,  23,  24]])

In [165]:
a = np.array([1,2])
b = np.ones(2,dtype=int)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[2 3]
[0 1]
[1 2]
[1. 2.]


In [168]:
x = np.array([[1,2],[3,4]])
x.sum(axis=1)

array([3, 7])

In [169]:
x.sum(axis=0)

array([4, 6])

In [171]:
x*1.6 

array([[1.6, 3.2],
       [4.8, 6.4]])

In [172]:
x.max()

4

In [173]:
x.min()

1

In [181]:
x = np.random.random(3)
x 

array([0.14724314, 0.50588295, 0.55251924])

In [193]:
np.random.randint(10,size=(2,6))

array([[4, 8, 3, 1, 4, 5],
       [4, 5, 0, 4, 9, 0]])

In [194]:
rng = np.random.default_rng()
x = rng.integers(3,size=(2,5))
x 

array([[0, 1, 1, 2, 1],
       [2, 1, 2, 1, 0]], dtype=int64)

In [195]:
np.vander(np.linspace(0, 2, 5), 3)

array([[0.  , 0.  , 1.  ],
       [0.25, 0.5 , 1.  ],
       [1.  , 1.  , 1.  ],
       [2.25, 1.5 , 1.  ],
       [4.  , 2.  , 1.  ]])